name: sapiens-dedicated-server
services:
  sapiens-server:
    # build: .
    image: devidian/sapiens:latest
    container_name: sapiens-ds-docker
    restart: unless-stopped
    volumes:
      # if you dont want to access files on your host machine you can comment this section
      # left side: your docker-host machine
      # right side: the paths in the image (!!do not change!!)
      - /appdata/sapiens/data:/home/sapiens/.local/share/majicjungle/sapiens
      - /appdata/sapiens/server:/appdata/sapiens/server
    ports:
      - 16161:16161/udp
      - 16162:16162/udp
      - 16168:16168/tcp
    environment: 
      - WORLD_NAME=MyCoolSapiensWorld
      - WORLD_SEED=MyCoolSeed
      # optional args, leave empty if you dont use them
      - ARG_DEBUG=-Y
      - ARG_ADVERTISE=-a
      # usage: --server-id SERVER_ID (-u) can optionally be supplied to control the player directory name where the worlds are saved. Should ideally be unique to the server, but can be anything that can be used as a directory name. If not supplied, a random string is generated and used.
      # example: ARG_SERVER_ID=-u MyName
      - ARG_SERVER_ID=
      # if you want to change ports, do not forget to adjust ports above
      - ARG_PORT=
      - ARG_HTTP=